server:
  port: 8083
spring:
  application:
    name: "Report"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
entrypoint:
  sqs:
    region: "us-east-1"
    endpoint: "http://localhost:4566"
    queueUrl: "https://sqs.us-east-1.amazonaws.com/842832773753/loan-approved-events-queue"
    waitTimeSeconds: 20
    maxNumberOfMessages: 1
    visibilityTimeoutSeconds: 30
    numberOfThreads: 1
adapters:
  dynamodb:
    tableName: "LoanReports"
    # El endpoint es para desarrollo local con LocalStack, coméntalo para producción
    endpoint: "http://localhost:4566"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  dynamodb:
    endpoint: "http://localhost:8000"
